global using System.Globalization;
global using System.Text;
global using Ardalis.GuardClauses;
global using Ardalis.Result;
global using Ardalis.Result.AspNetCore;
global using FastEndpoints;
global using FastEndpoints.Swagger;
global using Makc.Dummy.Gateway.Apps.WebApp.App;
global using Makc.Dummy.Gateway.Apps.WebApp.App.Config;
global using Makc.Dummy.Gateway.DomainModel.App;
global using Makc.Dummy.Gateway.DomainUseCases.App;
global using Makc.Dummy.Gateway.DomainUseCases.Auth.Actions.Login;
global using Makc.Dummy.Gateway.DomainUseCases.Auth.DTOs;
global using Makc.Dummy.Gateway.DomainUseCasesForReader.DummyItem;
global using Makc.Dummy.Gateway.DomainUseCasesForWriter.App;
global using Makc.Dummy.Gateway.DomainUseCasesForWriter.DummyItem;
global using Makc.Dummy.Gateway.Infrastructure.Core.App;
global using Makc.Dummy.Gateway.Infrastructure.GrpcForWriter.App;
global using Makc.Dummy.Gateway.Infrastructure.HttpForKeycloak.App;
global using Makc.Dummy.Gateway.Infrastructure.HttpForWriter.App;
global using Makc.Dummy.Shared.Apps.WebApp.App.Middlewares;
global using Makc.Dummy.Shared.Core.App;
global using Makc.Dummy.Shared.Core.App.Config.Options;
global using Makc.Dummy.Shared.Core.App.Config.Options.Enums;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections;
global using Makc.Dummy.Shared.DomainUseCases.Query.Sections;
global using Makc.Dummy.Shared.Infrastructure.Core.App;
global using Makc.Dummy.Shared.Infrastructure.Core.App.Logger.Funcs;
global using Makc.Dummy.Shared.Infrastructure.CoreForOpenTelemetry.App;
global using Makc.Dummy.Shared.Infrastructure.CoreForOpenTelemetryInWeb.App;
global using MediatR;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Logging;
global using Microsoft.IdentityModel.Tokens;
global using DummyItemCreateActionCommandForWriter = Makc.Dummy.Gateway.DomainUseCasesForWriter.DummyItem.Actions.Create.DummyItemCreateActionCommand;
global using DummyItemDeleteActionCommandForWriter = Makc.Dummy.Gateway.DomainUseCasesForWriter.DummyItem.Actions.Delete.DummyItemDeleteActionCommand;
global using DummyItemGetActionQueryForReader = Makc.Dummy.Gateway.DomainUseCasesForReader.DummyItem.Actions.Get.DummyItemGetActionQuery;
global using DummyItemGetActionQueryForWriter = Makc.Dummy.Gateway.DomainUseCasesForWriter.DummyItem.Actions.Get.DummyItemGetActionQuery;
global using DummyItemGetListActionQueryFilterForReader = Makc.Dummy.Gateway.DomainUseCasesForReader.DummyItem.Actions.GetList.Query.DummyItemGetListActionQueryFilter;
global using DummyItemGetListActionQueryFilterForWriter = Makc.Dummy.Gateway.DomainUseCasesForWriter.DummyItem.Actions.GetList.Query.DummyItemGetListActionQueryFilter;
global using DummyItemGetListActionQueryForReader = Makc.Dummy.Gateway.DomainUseCasesForReader.DummyItem.Actions.GetList.DummyItemGetListActionQuery;
global using DummyItemGetListActionQueryForWriter = Makc.Dummy.Gateway.DomainUseCasesForWriter.DummyItem.Actions.GetList.DummyItemGetListActionQuery;
global using DummyItemListDTOForReader = Makc.Dummy.Gateway.DomainUseCasesForReader.DummyItem.DTOs.DummyItemListDTO;
global using DummyItemListDTOForWriter = Makc.Dummy.Gateway.DomainUseCasesForWriter.DummyItem.DTOs.DummyItemListDTO;
global using DummyItemSingleDTOForReader = Makc.Dummy.Gateway.DomainUseCasesForReader.DummyItem.DTOs.DummyItemSingleDTO;
global using DummyItemSingleDTOForWriter = Makc.Dummy.Gateway.DomainUseCasesForWriter.DummyItem.DTOs.DummyItemSingleDTO;
global using DummyItemUpdateActionCommandForWriter = Makc.Dummy.Gateway.DomainUseCasesForWriter.DummyItem.Actions.Update.DummyItemUpdateActionCommand;
