global using System.Globalization;
global using System.Text;
global using Ardalis.GuardClauses;
global using Ardalis.Result;
global using Ardalis.Result.AspNetCore;
global using FastEndpoints;
global using FastEndpoints.Swagger;
global using Makc.Dummy.Gateway.Apps.WebApp.App;
global using Makc.Dummy.Gateway.Apps.WebApp.App.Config;
global using Makc.Dummy.Gateway.Apps.WebApp.App.Config.Options.Sections;
global using Makc.Dummy.Gateway.DomainModel.App;
global using Makc.Dummy.Gateway.DomainUseCases.App;
global using Makc.Dummy.Gateway.DomainUseCases.Auth.Actions.Login;
global using Makc.Dummy.Gateway.DomainUseCases.Auth.DTOs;
global using Makc.Dummy.Gateway.DomainUseCasesForMicroserviceReader.App;
global using Makc.Dummy.Gateway.DomainUseCasesForMicroserviceReader.DummyItem;
global using Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.App;
global using Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem;
global using Makc.Dummy.Gateway.Infrastructure.Core.App;
global using Makc.Dummy.Gateway.Infrastructure.GrpcForMicroserviceReader.App;
global using Makc.Dummy.Gateway.Infrastructure.GrpcForMicroserviceWriter.App;
global using Makc.Dummy.Gateway.Infrastructure.HttpForKeycloak.App;
global using Makc.Dummy.Gateway.Infrastructure.HttpForMicroserviceReader.App;
global using Makc.Dummy.Gateway.Infrastructure.HttpForMicroserviceWriter.App;
global using Makc.Dummy.Shared.Apps.WebApp.App.Middlewares;
global using Makc.Dummy.Shared.Core.App;
global using Makc.Dummy.Shared.Core.App.Config.Options;
global using Makc.Dummy.Shared.Core.App.Config.Options.Enums;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections.Domain;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections.Infrastructure;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections.Integration.Microservice.Reader;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections.Integration.Microservice.Writer;
global using Makc.Dummy.Shared.DomainUseCases.Query.Sections;
global using Makc.Dummy.Shared.Infrastructure.Core.App;
global using Makc.Dummy.Shared.Infrastructure.Core.App.Logger.Funcs;
global using Makc.Dummy.Shared.Infrastructure.CoreForOpenTelemetry.App;
global using Makc.Dummy.Shared.Infrastructure.CoreForOpenTelemetryInWeb.App;
global using MediatR;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Logging;
global using Microsoft.IdentityModel.Tokens;
global using DummyItemCreateActionCommandForMicroserviceWriter = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Actions.Create.DummyItemCreateActionCommand;
global using DummyItemDeleteActionCommandForMicroserviceWriter = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Actions.Delete.DummyItemDeleteActionCommand;
global using DummyItemGetActionQueryForMicroserviceReader = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceReader.DummyItem.Actions.Get.DummyItemGetActionQuery;
global using DummyItemGetActionQueryForMicroserviceWriter = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Actions.Get.DummyItemGetActionQuery;
global using DummyItemGetListActionQueryFilterForMicroserviceReader = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceReader.DummyItem.Actions.GetList.Query.DummyItemGetListActionQueryFilter;
global using DummyItemGetListActionQueryFilterForMicroserviceWriter = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Actions.GetList.Query.DummyItemGetListActionQueryFilter;
global using DummyItemGetListActionQueryForMicroserviceReader = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceReader.DummyItem.Actions.GetList.DummyItemGetListActionQuery;
global using DummyItemGetListActionQueryForMicroserviceWriter = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Actions.GetList.DummyItemGetListActionQuery;
global using DummyItemListDTOForMicroserviceReader = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceReader.DummyItem.DTOs.DummyItemListDTO;
global using DummyItemListDTOForMicroserviceWriter = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.DTOs.DummyItemListDTO;
global using DummyItemSingleDTOForMicroserviceReader = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceReader.DummyItem.DTOs.DummyItemSingleDTO;
global using DummyItemSingleDTOForMicroserviceWriter = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.DTOs.DummyItemSingleDTO;
global using DummyItemUpdateActionCommandForMicroserviceWriter = Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Actions.Update.DummyItemUpdateActionCommand;
