global using Confluent.Kafka;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections;
global using Makc.Dummy.Shared.Core.Message;
global using Makc.Dummy.Shared.Infrastructure.Kafka.Message;
global using Makc.Dummy.Writer.DomainUseCases.App.Message;
global using Makc.Dummy.Writer.Infrastructure.Kafka.App.Config.Options.Sections;
global using Makc.Dummy.Writer.Infrastructure.Kafka.App.Message;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
