services:
  backend-gateway-web-app:
    container_name: ${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_IMAGE_NAME}
    environment:
      - App__Authentication__Key=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_AUTHENTICATION_KEY}
      - App__Keycloak__BaseUrl=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_KEYCLOAK_BASE_URL}
      - App__Keycloak__ClientSecret=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_KEYCLOAK_CLIENT_SECRET}
      - App__Observability__CollectorGrpcEndpoint=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_OBSERVABILITY_COLLECTOR_GRPC_ENDPOINT}
      - App__Observability__CollectorHttpEndpoint=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_OBSERVABILITY_COLLECTOR_HTTP_ENDPOINT}
      - App__Reader__GrpcEndpoint=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_READER_GRPC_ENDPOINT}
      - App__Reader__HttpEndpoint=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_READER_HTTP_ENDPOINT}
      - App__Writer__GrpcEndpoint=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_WRITER_GRPC_ENDPOINT}
      - App__Writer__HttpEndpoint=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_WRITER_HTTP_ENDPOINT}
    networks:
      - network-backend
    depends_on:
      backend-writer-web-app:
        condition: service_started