services:
  backend-reader-inbox-cleaner-app:
    container_name: ${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_IMAGE_NAME}
    environment:
      - App__MongoDB__Password=${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONFIG_MONGODB_PASSWORD}
      - App__MongoDB__Port=${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONFIG_MONGODB_PORT}
      - App__MongoDB__Server=${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONFIG_MONGODB_SERVER}
      - App__MongoDB__UserId=${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONFIG_MONGODB_USERID}
      - App__Observability__CollectorGrpcEndpoint=${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONFIG_OBSERVABILITY_COLLECTOR_GRPC_ENDPOINT}
      - App__Observability__CollectorHttpEndpoint=${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONFIG_OBSERVABILITY_COLLECTOR_HTTP_ENDPOINT}
    networks:
      - network-backend

  backend-reader-inbox-consumer-app:
    container_name: ${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_IMAGE_NAME}
    environment:
      - App__Kafka__Consumer__BootstrapServers=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_KAFKA_BOOTSTRAP_SERVERS}
      - App__MongoDB__Password=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_MONGODB_PASSWORD}
      - App__MongoDB__Port=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_MONGODB_PORT}
      - App__MongoDB__Server=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_MONGODB_SERVER}
      - App__MongoDB__UserId=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_MONGODB_USERID}
      - App__Observability__CollectorGrpcEndpoint=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_OBSERVABILITY_COLLECTOR_GRPC_ENDPOINT}
      - App__Observability__CollectorHttpEndpoint=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_OBSERVABILITY_COLLECTOR_HTTP_ENDPOINT}
      - App__RabbitMQ__HostName=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_RABBITMQ_HOSTNAME}
      - App__RabbitMQ__Password=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_RABBITMQ_PASSWORD}
      - App__RabbitMQ__Port=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_RABBITMQ_PORT}
      - App__RabbitMQ__UserName=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_RABBITMQ_USERNAME}
    networks:
      - network-backend

  backend-reader-web-app:
    container_name: ${MY_SERVICE_BACKEND_READER_WEB_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_READER_WEB_APP_IMAGE_NAME}
    environment:
      - App__Authentication__Key=${MY_SERVICE_BACKEND_READER_WEB_APP_CONFIG_AUTHENTICATION_KEY}
      - App__MongoDB__Password=${MY_SERVICE_BACKEND_READER_WEB_APP_CONFIG_MONGODB_PASSWORD}
      - App__MongoDB__Port=${MY_SERVICE_BACKEND_READER_WEB_APP_CONFIG_MONGODB_PORT}
      - App__MongoDB__Server=${MY_SERVICE_BACKEND_READER_WEB_APP_CONFIG_MONGODB_SERVER}
      - App__MongoDB__UserId=${MY_SERVICE_BACKEND_READER_WEB_APP_CONFIG_MONGODB_USERID}
      - App__Observability__CollectorGrpcEndpoint=${MY_SERVICE_BACKEND_READER_WEB_APP_CONFIG_OBSERVABILITY_COLLECTOR_GRPC_ENDPOINT}
      - App__Observability__CollectorHttpEndpoint=${MY_SERVICE_BACKEND_READER_WEB_APP_CONFIG_OBSERVABILITY_COLLECTOR_HTTP_ENDPOINT}
    networks:
      - network-backend

networks:
  network-backend:
    attachable: true
