services:
  backend-writer-db-migration-for-mssqlserver-app:
    container_name: ${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_FOR_MSSQLSERVER_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_IMAGE_NAME}
    environment:
      - App__Domain__App__Db=MSSQLServer
      - App__Infrastructure__MSSQLServer__Password=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_PASSWORD}
      - App__Infrastructure__MSSQLServer__Port=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_PORT}
      - App__Infrastructure__MSSQLServer__Server=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_SERVER}
      - App__Infrastructure__MSSQLServer__UserId=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_USERID}
      - App__Infrastructure__Observability__CollectorGrpcEndpoint=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_COLLECTOR_GRPC_ENDPOINT}
      - App__Infrastructure__Observability__CollectorHttpEndpoint=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_COLLECTOR_HTTP_ENDPOINT}
      - App__Infrastructure__Observability__ServiceName=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_FOR_MSSQLSERVER_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_SERVICE_NAME}
      - App__Workloads=["AppDbMigration"]
    networks:
      - network-backend

  backend-writer-db-migration-for-postgres-app:
    container_name: ${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_FOR_POSTGRES_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_IMAGE_NAME}
    environment:
      - App__Domain__App__Db=PostgreSQL
      - App__Infrastructure__Observability__CollectorGrpcEndpoint=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_COLLECTOR_GRPC_ENDPOINT}
      - App__Infrastructure__Observability__CollectorHttpEndpoint=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_COLLECTOR_HTTP_ENDPOINT}
      - App__Infrastructure__Observability__ServiceName=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_FOR_POSTGRES_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_SERVICE_NAME}
      - App__Infrastructure__PostgreSQL__Password=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_PASSWORD}
      - App__Infrastructure__PostgreSQL__Port=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_PORT}
      - App__Infrastructure__PostgreSQL__Server=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_SERVER}
      - App__Infrastructure__PostgreSQL__UserId=${MY_SERVICE_BACKEND_WRITER_DB_MIGRATION_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_USERID}
      - App__Workloads=["AppDbMigration"]
    networks:
      - network-backend

  backend-writer-outbox-cleaner-app:
    container_name: ${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_IMAGE_NAME}
    environment:
      - App__Infrastructure__MSSQLServer__Password=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_PASSWORD}
      - App__Infrastructure__MSSQLServer__Port=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_PORT}
      - App__Infrastructure__MSSQLServer__Server=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_SERVER}
      - App__Infrastructure__MSSQLServer__UserId=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_USERID}
      - App__Infrastructure__Observability__CollectorGrpcEndpoint=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_COLLECTOR_GRPC_ENDPOINT}
      - App__Infrastructure__Observability__CollectorHttpEndpoint=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_COLLECTOR_HTTP_ENDPOINT}
      - App__Infrastructure__Observability__ServiceName=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_SERVICE_NAME}
      - App__Infrastructure__PostgreSQL__Password=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_PASSWORD}
      - App__Infrastructure__PostgreSQL__Port=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_PORT}
      - App__Infrastructure__PostgreSQL__Server=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_SERVER}
      - App__Infrastructure__PostgreSQL__UserId=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_USERID}
      - App__Workloads=["AppOutboxCleaner"]
    networks:
      - network-backend

  backend-writer-outbox-producer-app:
    container_name: ${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_IMAGE_NAME}
    environment:
      - App__Infrastructure__Kafka__Producer__BootstrapServers=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_KAFKA_BOOTSTRAP_SERVERS}
      - App__Infrastructure__MSSQLServer__Password=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_PASSWORD}
      - App__Infrastructure__MSSQLServer__Port=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_PORT}
      - App__Infrastructure__MSSQLServer__Server=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_SERVER}
      - App__Infrastructure__MSSQLServer__UserId=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_USERID}
      - App__Infrastructure__Observability__CollectorGrpcEndpoint=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_COLLECTOR_GRPC_ENDPOINT}
      - App__Infrastructure__Observability__CollectorHttpEndpoint=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_COLLECTOR_HTTP_ENDPOINT}
      - App__Infrastructure__Observability__ServiceName=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_SERVICE_NAME}
      - App__Infrastructure__PostgreSQL__Password=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_PASSWORD}
      - App__Infrastructure__PostgreSQL__Port=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_PORT}
      - App__Infrastructure__PostgreSQL__Server=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_SERVER}
      - App__Infrastructure__PostgreSQL__UserId=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_USERID}
      - App__Infrastructure__RabbitMQ__HostName=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_RABBITMQ_HOSTNAME}
      - App__Infrastructure__RabbitMQ__Password=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_RABBITMQ_PASSWORD}
      - App__Infrastructure__RabbitMQ__Port=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_RABBITMQ_PORT}
      - App__Infrastructure__RabbitMQ__UserName=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_INFRASTRUCTURE_RABBITMQ_USERNAME}
      - App__Workloads=["AppOutboxProducer"]
    networks:
      - network-backend
      
  backend-writer-web-app:
    container_name: ${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_WRITER_WEB_APP_IMAGE_NAME}
    environment:
      - App__Domain__Auth__Key=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_DOMAIN_AUTH_KEY}
      - App__Infrastructure__MSSQLServer__Password=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_PASSWORD}
      - App__Infrastructure__MSSQLServer__Port=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_PORT}
      - App__Infrastructure__MSSQLServer__Server=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_SERVER}
      - App__Infrastructure__MSSQLServer__UserId=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_INFRASTRUCTURE_MSSQLSERVER_USERID}
      - App__Infrastructure__Observability__CollectorGrpcEndpoint=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_COLLECTOR_GRPC_ENDPOINT}
      - App__Infrastructure__Observability__CollectorHttpEndpoint=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_INFRASTRUCTURE_OBSERVABILITY_COLLECTOR_HTTP_ENDPOINT}
      - App__Infrastructure__PostgreSQL__Password=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_PASSWORD}
      - App__Infrastructure__PostgreSQL__Port=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_PORT}
      - App__Infrastructure__PostgreSQL__Server=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_SERVER}
      - App__Infrastructure__PostgreSQL__UserId=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_INFRASTRUCTURE_POSTGRESQL_USERID}
    networks:
      - network-backend

networks:
  network-backend:
    attachable: true
