global using Ardalis.Result;
global using Grpc.Core;
global using Makc.Dummy.Gateway.Domain.UseCasesForMicroserviceWriter.Auth.Commands;
global using Makc.Dummy.Gateway.Domain.UseCasesForMicroserviceWriter.Auth.DTOs;
global using Makc.Dummy.Gateway.Domain.UseCasesForMicroserviceWriter.Auth.Services;
global using Makc.Dummy.Gateway.Domain.UseCasesForMicroserviceWriter.DummyItem.Command.Sections;
global using Makc.Dummy.Gateway.Domain.UseCasesForMicroserviceWriter.DummyItem.Commands;
global using Makc.Dummy.Gateway.Domain.UseCasesForMicroserviceWriter.DummyItem.DTOs;
global using Makc.Dummy.Gateway.Domain.UseCasesForMicroserviceWriter.DummyItem.Queries;
global using Makc.Dummy.Gateway.Domain.UseCasesForMicroserviceWriter.DummyItem.Services;
global using Makc.Dummy.Gateway.Infrastructure.GrpcForMicroserviceWriter.Auth;
global using Makc.Dummy.Gateway.Infrastructure.GrpcForMicroserviceWriter.Auth.Services;
global using Makc.Dummy.Gateway.Infrastructure.GrpcForMicroserviceWriter.DummyItem.Services;
global using Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.Auth;
global using Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.DummyItem;
global using Makc.Dummy.Shared.Core.App;
global using Makc.Dummy.Shared.Core.App.Config.Options.Enums;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections.Domain;
global using Makc.Dummy.Shared.Core.Http;
global using Makc.Dummy.Shared.Infrastructure.Grpc;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using AuthGrpcClient = Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.Auth.Auth.AuthClient;
global using DummyItemGrpcClient = Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.DummyItem.DummyItem.DummyItemClient;
