global using Ardalis.Result;
global using Grpc.Core;
global using Makc.Dummy.Gateway.DomainUseCases.Auth.Actions.Login;
global using Makc.Dummy.Gateway.DomainUseCases.Auth.DTOs;
global using Makc.Dummy.Gateway.DomainUseCases.Auth.Services;
global using Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Actions.Create;
global using Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Actions.Delete;
global using Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Actions.Update;
global using Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.DTOs;
global using Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Queries;
global using Makc.Dummy.Gateway.DomainUseCasesForMicroserviceWriter.DummyItem.Services;
global using Makc.Dummy.Gateway.Infrastructure.GrpcForMicroserviceWriter.Auth;
global using Makc.Dummy.Gateway.Infrastructure.GrpcForMicroserviceWriter.Auth.Services;
global using Makc.Dummy.Gateway.Infrastructure.GrpcForMicroserviceWriter.DummyItem.Services;
global using Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.Auth;
global using Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.DummyItem;
global using Makc.Dummy.Shared.Core.App;
global using Makc.Dummy.Shared.Core.App.Config.Options.Enums;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections.Domain;
global using Makc.Dummy.Shared.Core.Http;
global using Makc.Dummy.Shared.Infrastructure.Grpc;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using AuthGrpcClient = Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.Auth.Auth.AuthClient;
global using DummyItemGrpcClient = Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.DummyItem.DummyItem.DummyItemClient;
