include:
  - docker-compose-kafka.yml
  - docker-compose-keycloak.yml
  - docker-compose-mssqlserver.yml
  - docker-compose-mongo.yml
  - docker-compose-observability.yml
  - docker-compose-postgres.yml
  - docker-compose-rabbitmq.yml

networks:
  network-backend:
    attachable: true

