services:
  external-mssqlserver:
    user: root #https://stackoverflow.com/questions/65601077/unable-to-run-sql-server-2019-docker-with-volumes-and-get-error-setup-failed-co
    volumes:
      - _mssqlserver_backup:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_BACKUP}
      - _mssqlserver_data:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_DATA}
      - _mssqlserver_dump:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_DUMP}
      - _mssqlserver_log:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_LOG}
    ports:
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_PORT}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_PORT}

volumes:
  _mssqlserver_backup:
  _mssqlserver_data:
  _mssqlserver_dump:
  _mssqlserver_log: