include:
  - docker-compose-kafka.override.yml
  - docker-compose-keycloak.override.yml
  - docker-compose-mssqlserver.override.yml
  - docker-compose-mongo.override.yml
  - docker-compose-observability.override.yml
  - docker-compose-postgres.override.yml
  - docker-compose-rabbitmq.override.yml