services:
  external-keycloak:
    volumes:
      - ${MY_SERVICE_EXTERNAL_KEYCLOAK_HOST_FOLDER_IMPORT}:${MY_SERVICE_EXTERNAL_KEYCLOAK_CONTAINER_FOLDER_IMPORT}
    ports:
      - ${MY_SERVICE_EXTERNAL_KEYCLOAK_HOST_PORT}:${MY_SERVICE_EXTERNAL_KEYCLOAK_CONTAINER_PORT}

  external-keycloak-postgres:
    volumes:
      - ${MY_SERVICE_EXTERNAL_KEYCLOAK_POSTGRES_HOST_FOLDER_DATA}:${MY_SERVICE_EXTERNAL_KEYCLOAK_POSTGRES_CONTAINER_FOLDER_DATA}
    ports:
      - ${MY_SERVICE_EXTERNAL_KEYCLOAK_POSTGRES_HOST_PORT}:${MY_SERVICE_EXTERNAL_KEYCLOAK_POSTGRES_CONTAINER_PORT}