services:
  external-mongo:
    build:
      context: src/mongo
      dockerfile: Dockerfile
      args:
        - APP_KEYFILE=${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_KEYFILE}
    command: --replSet ${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_REPLICASET} --keyFile ${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_KEYFILE} --bind_ip_all
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_REPLICASET}', members:[{_id:0, host:'${MY_LOCALHOST}:${MY_SERVICE_EXTERNAL_MONGO_HOST_PORT}'}]}) }"  | mongosh --port ${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_PORT} -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --quiet
      interval: 5s
      timeout: 15s
      start_period: 15s
      retries: 10
    volumes:
      - _mongo_config:${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_FOLDER_CONFIG}
      - _mongo_data_configdb:${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_FOLDER_DATA_CONFIGDB}
      - _mongo_data_db:${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_FOLDER_DATA_DB}
    ports:
      - ${MY_SERVICE_EXTERNAL_MONGO_HOST_PORT}:${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_PORT}

  external-mongo-express:
    ports:
      - ${MY_SERVICE_EXTERNAL_MONGO_EXPRESS_HOST_PORT}:${MY_SERVICE_EXTERNAL_MONGO_EXPRESS_CONTAINER_PORT}

volumes:
  _mongo_config:
  _mongo_data_configdb:
  _mongo_data_db: