services:
  external-mssqlserver:
    container_name: ${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_NAME}
    image: ${MY_SERVICE_EXTERNAL_MSSQLSERVER_IMAGE}
    environment:
      - ACCEPT_EULA
      - MSSQL_BACKUP_DIR
      - MSSQL_COLLATION
      - MSSQL_DATA_DIR
      - MSSQL_DUMP_DIR
      - MSSQL_LOG_DIR
      - MSSQL_PID
      - MSSQL_SA_PASSWORD
    networks:
      - network-backend