services:
  external-pgadmin:
    volumes:
      - _pgadmin:${MY_SERVICE_EXTERNAL_PGADMIN_CONTAINER_FOLDER}
    ports:
      - ${MY_SERVICE_EXTERNAL_PGADMIN_HOST_PORT}:${MY_SERVICE_EXTERNAL_PGADMIN_CONTAINER_PORT}

  external-postgres:
    volumes:
      - _postgres_data:${MY_SERVICE_EXTERNAL_POSTGRES_CONTAINER_FOLDER_DATA}
    ports:
      - ${MY_SERVICE_EXTERNAL_POSTGRES_HOST_PORT}:${MY_SERVICE_EXTERNAL_POSTGRES_CONTAINER_PORT}

volumes:
  _pgadmin:
  _postgres_data: