services:
  external-observability-grafana:
    ports:
      - ${MY_SERVICE_EXPERNAL_OBSERVABILITY_GRAFANA_HOST_PORT}:${MY_SERVICE_EXPERNAL_OBSERVABILITY_GRAFANA_CONTAINER_PORT}
    volumes:
      - ${MY_SERVICE_EXPERNAL_OBSERVABILITY_GRAFANA_HOST_DATASOURCES_FILE}:${MY_SERVICE_EXPERNAL_OBSERVABILITY_GRAFANA_CONTAINER_DATASOURCES_FILE}
      - _observability_grafana:${MY_SERVICE_EXTERNAL_OBSERVABILITY_GRAFANA_CONTAINER_FOLDER}

  external-observability-jaeger:
    volumes:
      - _observability_jaeger:${MY_SERVICE_EXTERNAL_OBSERVABILITY_JAEGER_CONTAINER_FOLDER}
    ports:
      - ${MY_SERVICE_EXPERNAL_OBSERVABILITY_JAEGER_HOST_PORT}:${MY_SERVICE_EXPERNAL_OBSERVABILITY_JAEGER_CONTAINER_PORT} # Jaeger UI

  external-observability-loki:
    volumes:
      - _observability_loki:${MY_SERVICE_EXTERNAL_OBSERVABILITY_LOKI_CONTAINER_FOLDER}

  external-observability-otel-collector:
    volumes:
      - ${MY_SERVICE_EXPERNAL_OBSERVABILITY_OTEL_COLLECTOR_HOST_CONFIG_FILE}:${MY_SERVICE_EXPERNAL_OBSERVABILITY_OTEL_COLLECTOR_CONTAINER_CONFIG_FILE}
    ports:
      - ${MY_SERVICE_EXPERNAL_OBSERVABILITY_OTEL_COLLECTOR_HOST_PORT_GRPC}:${MY_SERVICE_EXPERNAL_OBSERVABILITY_OTEL_COLLECTOR_CONTAINER_PORT_GRPC} # OTLP over gRPC receiver
      - ${MY_SERVICE_EXPERNAL_OBSERVABILITY_OTEL_COLLECTOR_HOST_PORT_HTTP}:${MY_SERVICE_EXPERNAL_OBSERVABILITY_OTEL_COLLECTOR_CONTAINER_PORT_HTTP} # OTLP over HTTP receiver
      # - "9464"          # Prometheus exporter
      # - "8888"          # metrics endpoint
      # - 1888:1888 # pprof extension
      # - 13133:13133 # health_check extension
      # - 55679:55679 # zpages extension
      # - 8888:8888 # Prometheus metrics exposed by the collector
      # - 8889:8889 # Prometheus exporter metrics
      # - 4317:4317 # OTLP gRPC receiver
      # - 4318:4318 # OTLP http receiver

  external-observability-prometheus:
    volumes:
      - ${MY_SERVICE_EXPERNAL_OBSERVABILITY_PROMETHEUS_HOST_CONFIG_FILE}:${MY_SERVICE_EXPERNAL_OBSERVABILITY_PROMETHEUS_CONTAINER_CONFIG_FILE}
      - _observability_prometheus:${MY_SERVICE_EXTERNAL_OBSERVABILITY_PROMETHEUS_CONTAINER_FOLDER}
    ports:
      - ${MY_SERVICE_EXPERNAL_OBSERVABILITY_PROMETHEUS_HOST_PORT}:${MY_SERVICE_EXPERNAL_OBSERVABILITY_PROMETHEUS_CONTAINER_PORT}

  external-observability-zipkin:
    volumes:
      - _observability_zipkin:${MY_SERVICE_EXTERNAL_OBSERVABILITY_ZIPKIN_CONTAINER_FOLDER}
    ports:
      - ${MY_SERVICE_EXPERNAL_OBSERVABILITY_ZIPKIN_HOST_PORT}:${MY_SERVICE_EXPERNAL_OBSERVABILITY_ZIPKIN_CONTAINER_PORT}

volumes:
  _observability_grafana:
  _observability_jaeger:
  _observability_loki:
  _observability_prometheus:
  _observability_zipkin:
