services:
  external-mssqlserver:
    volumes:
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_FOLDER_BACKUP}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_BACKUP}
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_FOLDER_DATA}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_DATA}
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_FOLDER_DUMP}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_DUMP}
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_FOLDER_LOG}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_LOG}
    ports:
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_PORT}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_PORT}