services:
  external-observability-grafana:
    container_name: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_GRAFANA_CONTAINER_NAME}
    image: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_GRAFANA_IMAGE}
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED
      - GF_AUTH_ANONYMOUS_ORG_ROLE
      - GF_AUTH_DISABLE_LOGIN_FORM
    depends_on:
      - external-observability-jaeger
      - external-observability-loki
      - external-observability-otel-collector
      - external-observability-prometheus
      - external-observability-zipkin
    networks:
      - network-backend

  external-observability-jaeger:
    container_name: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_JAEGER_CONTAINER_NAME}
    image: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_JAEGER_IMAGE}
    networks:
      - network-backend

  external-observability-loki:
    container_name: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_LOKI_CONTAINER_NAME}
    image: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_LOKI_IMAGE}
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    networks:
      - network-backend

  external-observability-otel-collector:
    container_name: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_OTEL_COLLECTOR_CONTAINER_NAME}
    image: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_OTEL_COLLECTOR_IMAGE}
    command: [ "--config=${MY_SERVICE_EXPERNAL_OBSERVABILITY_OTEL_COLLECTOR_CONTAINER_CONFIG_FILE}" ]
    depends_on:
      - external-observability-jaeger
      - external-observability-loki
      - external-observability-prometheus
      - external-observability-zipkin
    networks:
      - network-backend

  external-observability-prometheus:
    container_name: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_PROMETHEUS_CONTAINER_NAME}
    image: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_PROMETHEUS_IMAGE}
    command: 
      - '--config.file=${MY_SERVICE_EXPERNAL_OBSERVABILITY_PROMETHEUS_CONTAINER_CONFIG_FILE}'
      - '--web.listen-address=:${MY_SERVICE_EXPERNAL_OBSERVABILITY_PROMETHEUS_CONTAINER_PORT}'
    environment:
      - config.file=${MY_SERVICE_EXPERNAL_OBSERVABILITY_PROMETHEUS_CONTAINER_CONFIG_FILE}
    networks:
      - network-backend

  external-observability-zipkin:
    container_name: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_ZIPKIN_CONTAINER_NAME}
    image: ${MY_SERVICE_EXTERNAL_OBSERVABILITY_ZIPKIN_IMAGE}
    networks:
      - network-backend