include:
  - docker-compose.observability.override.yaml

services:
  external-keycloak:
    volumes:
      - ${MY_SERVICE_EXTERNAL_KEYCLOAK_HOST_FOLDER_IMPORT}:${MY_SERVICE_EXTERNAL_KEYCLOAK_CONTAINER_FOLDER_IMPORT}
    ports:
      - ${MY_SERVICE_EXTERNAL_KEYCLOAK_HOST_PORT}:${MY_SERVICE_EXTERNAL_KEYCLOAK_CONTAINER_PORT}

  external-keycloak-postgres:
    volumes:
      - ${MY_SERVICE_EXTERNAL_KEYCLOAK_POSTGRES_HOST_FOLDER_DATA}:${MY_SERVICE_EXTERNAL_KEYCLOAK_POSTGRES_CONTAINER_FOLDER_DATA}
    ports:
      - ${MY_SERVICE_EXTERNAL_KEYCLOAK_POSTGRES_HOST_PORT}:${MY_SERVICE_EXTERNAL_KEYCLOAK_POSTGRES_CONTAINER_PORT}

  external-mongo:
    volumes:
      - ${MY_SERVICE_EXTERNAL_MONGO_HOST_FOLDER}:${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_FOLDER}
    ports:
      - ${MY_SERVICE_EXTERNAL_MONGO_HOST_PORT}:${MY_SERVICE_EXTERNAL_MONGO_CONTAINER_PORT}

  external-mongo-express:
    ports:
      - ${MY_SERVICE_EXTERNAL_MONGO_EXPRESS_HOST_PORT}:${MY_SERVICE_EXTERNAL_MONGO_EXPRESS_CONTAINER_PORT}

  external-mssqlserver:
    volumes:
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_FOLDER_BACKUP}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_BACKUP}
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_FOLDER_DATA}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_DATA}
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_FOLDER_DUMP}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_DUMP}
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_FOLDER_LOG}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_FOLDER_LOG}
    ports:
      - ${MY_SERVICE_EXTERNAL_MSSQLSERVER_HOST_PORT}:${MY_SERVICE_EXTERNAL_MSSQLSERVER_CONTAINER_PORT}

  external-pgadmin:
    volumes:
      - ${MY_SERVICE_EXTERNAL_PGADMIN_HOST_FOLDER}:${MY_SERVICE_EXTERNAL_PGADMIN_CONTAINER_FOLDER}
    ports:
      - ${MY_SERVICE_EXTERNAL_PGADMIN_HOST_PORT}:${MY_SERVICE_EXTERNAL_PGADMIN_CONTAINER_PORT}

  external-postgres:
    volumes:
      - ${MY_SERVICE_EXTERNAL_POSTGRES_HOST_FOLDER_DATA}:${MY_SERVICE_EXTERNAL_POSTGRES_CONTAINER_FOLDER_DATA}
    ports:
      - ${MY_SERVICE_EXTERNAL_POSTGRES_HOST_PORT}:${MY_SERVICE_EXTERNAL_POSTGRES_CONTAINER_PORT}

  external-rabbitmq:
    volumes:
      - ${MY_SERVICE_EXTERNAL_RABBITMQ_HOST_FOLDER}:${MY_SERVICE_EXTERNAL_RABBITMQ_CONTAINER_FOLDER}
    ports:
      - ${MY_SERVICE_EXTERNAL_RABBITMQ_HOST_PORT}:${MY_SERVICE_EXTERNAL_RABBITMQ_CONTAINER_PORT}
      - ${MY_SERVICE_EXTERNAL_RABBITMQ_MANAGEMENT_HOST_PORT}:${MY_SERVICE_EXTERNAL_RABBITMQ_MANAGEMENT_CONTAINER_PORT}