// <auto-generated />
using System;
using Makc.Dummy.MicroserviceWriterViaSQL.Infrastructure.EntityFramework.App.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Makc.Dummy.MicroserviceWriterViaSQL.Infrastructure.EntityFrameworkForPostgreSQL.App.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Makc.Dummy.MicroserviceWriterViaSQL.Domain.Model.AppOutgoingEvent.AppOutgoingEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("сoncurrency_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id")
                        .HasName("pk_app_outgoing_event");

                    b.ToTable("app_outgoing_event", "writer");
                });

            modelBuilder.Entity("Makc.Dummy.MicroserviceWriterViaSQL.Domain.Model.AppOutgoingEventPayload.AppOutgoingEventPayloadEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppOutgoingEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_outgoing_event_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("сoncurrency_token");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("EntityConcurrencyTokenToDelete")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("entity_concurrency_token_to_delete");

                    b.Property<string>("EntityConcurrencyTokenToInsert")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("entity_concurrency_token_to_insert");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_app_outgoing_event_payload");

                    b.HasIndex("AppOutgoingEventId");

                    b.ToTable("app_outgoing_event_payload", "writer");
                });

            modelBuilder.Entity("Makc.Dummy.MicroserviceWriterViaSQL.Domain.Model.DummyItem.DummyItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("сoncurrency_token");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_dummy_item");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_dummy_item_name");

                    b.ToTable("dummy_item", "writer");
                });

            modelBuilder.Entity("Makc.Dummy.MicroserviceWriterViaSQL.Domain.Model.AppOutgoingEventPayload.AppOutgoingEventPayloadEntity", b =>
                {
                    b.HasOne("Makc.Dummy.MicroserviceWriterViaSQL.Domain.Model.AppOutgoingEvent.AppOutgoingEventEntity", "AppOutgoingEvent")
                        .WithMany("Payloads")
                        .HasForeignKey("AppOutgoingEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_outgoing_event_payload_app_outgoing_event");

                    b.Navigation("AppOutgoingEvent");
                });

            modelBuilder.Entity("Makc.Dummy.MicroserviceWriterViaSQL.Domain.Model.AppOutgoingEvent.AppOutgoingEventEntity", b =>
                {
                    b.Navigation("Payloads");
                });
#pragma warning restore 612, 618
        }
    }
}
