global using Google.Protobuf.WellKnownTypes;
global using Grpc.Core;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEvent.Actions.Delete;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEvent.Actions.Get;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEvent.Actions.GetList;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEvent.Actions.Save;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEvent.DTOs;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEvent.Queries;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEventPayload.Actions.Delete;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEventPayload.Actions.Get;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEventPayload.Actions.GetList;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEventPayload.Actions.Save;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEventPayload.DTOs;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.AppOutgoingEventPayload.Queries;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.Auth.Actions.Login;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.Auth.DTOs;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.DummyItem.Actions.Delete;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.DummyItem.Actions.Get;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.DummyItem.Actions.GetList;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.DummyItem.Actions.Save;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.DummyItem.Commands;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.DummyItem.DTOs;
global using Makc.Dummy.MicroserviceWriter.DomainUseCases.DummyItem.Queries;
global using Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.AppOutgoingEvent;
global using Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.AppOutgoingEventPayload;
global using Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.Auth;
global using Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.DummyItem;
global using Makc.Dummy.Shared.Core.App.Event.Payloads;
global using Makc.Dummy.Shared.Infrastructure.Grpc;
global using MediatR;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using AppOutgoingEventPayloadServiceBase = Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.AppOutgoingEventPayload.AppOutgoingEventPayload.AppOutgoingEventPayloadBase;
global using AppOutgoingEventServiceBase = Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.AppOutgoingEvent.AppOutgoingEvent.AppOutgoingEventBase;
global using AuthServiceBase = Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.Auth.Auth.AuthBase;
global using DummyItemServiceBase = Makc.Dummy.MicroserviceWriter.Infrastructure.Grpc.DummyItem.DummyItem.DummyItemBase;
