global using System.Globalization;
global using Ardalis.GuardClauses;
global using Makc.Dummy.Reader.Apps.InboxCleanerApp.App;
global using Makc.Dummy.Reader.Apps.InboxCleanerApp.App.Config;
global using Makc.Dummy.Reader.Infrastructure.Core.App;
global using Makc.Dummy.Shared.Core.App;
global using Makc.Dummy.Shared.Core.App.Config.Options;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections.Db.PostgreSQL;
global using Microsoft.Extensions.Options;
