global using System.Collections.Concurrent;
global using System.Text;
global using System.Threading.Channels;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections;
global using Makc.Dummy.Shared.Core.Message;
global using Makc.Dummy.Writer.Infrastructure.RabbitMQ.App.Message;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using RabbitMQ.Client;
