worker_processes auto;

pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Logging
    access_log off;
    error_log  /dev/stderr warn;

    # Performance
    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    keepalive_requests 1000;

    # Compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_min_length 256;
    gzip_comp_level 6;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        font/ttf
        font/otf
        image/svg+xml;

    # https://angular.dev/guide/i18n/deploy
    # Browser preferred language detection (does NOT require
    # AcceptLanguageModule)
    map $http_accept_language $accept_language {
        ~*^en en;
        ~*^ru "";
    }

    server {
        listen       8080;
        server_name  localhost;

        root /usr/share/nginx/html;
        index index.html;

        # # Angular Routing
        # location / {
        #     try_files $uri $uri/ /index.html;
        # }
        # https://angular.dev/guide/i18n/deploy
        # Fallback to default language if no preference defined by browser
        if ($accept_language ~ "^$") {
            set $accept_language "ru";
        }
        # Redirect "/" to Angular application in the preferred language of the browser
        rewrite ^/$ /$accept_language permanent;
        # Everything under the Angular application is always redirected to Angular in the
        # correct language
        location ~ ^/(ru|en|$) {
            # "try_files" directive is not allowed here
            # if ($accept_language = "ru") {
            #     try_files $uri /index.html?$args;
            # }
            try_files $uri /$1/index.html?$args;
        }

        # Static Assets Caching
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|map)$ {
            expires 1y;
            access_log off;
            add_header Cache-Control "public, immutable";
        }

        # Optional: Explicit asset route
        location /assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}
