global using System.Text;
global using Makc.Dummy.Shared.Core.App.Config.Options.Sections.Infrastructure;
global using Makc.Dummy.Shared.Core.Message;
global using Makc.Dummy.Shared.Infrastructure.RabbitMQ.Message;
global using Makc.Dummy.MicroserviceWriterViaSQL.Domain.UseCases.App.Message;
global using Makc.Dummy.MicroserviceWriterViaSQL.Infrastructure.RabbitMQ.App.Message;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using RabbitMQ.Client;
